# Generated by Django 4.2.30 on 2026-05-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Título')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='Categoria/Tipo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('section', models.CharField(choices=[('featured_main', 'Destaque Principal (Alto)'), ('featured_side', 'Destaque Secundário (Médio)'), ('gallery_small', 'Galeria (Grade 3)'), ('gallery_asym', 'Galeria (Assimétrico)'), ('reel', 'Reel Clip')], max_length=20, verbose_name='Secção no Site')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('media_file', models.FileField(upload_to='projects_media/', verbose_name='Ficheiro (Imagem/Vídeo)')),
                ('is_video', models.BooleanField(default=False, verbose_name='É vídeo?')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
