# Generated by Django 4.2.30 on 2026-05-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreativeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.CharField(help_text='Ex: 01, 02', max_length=10, verbose_name='Número do Passo')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Passo do Processo',
                'verbose_name_plural': 'Processo Criativo',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GeneralSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_year', models.CharField(default='2025', max_length=10, verbose_name='Ano no Hero')),
                ('hero_title', models.TextField(default='Marcas que<br><span class="blue">ficam</span><br>na memória.', verbose_name='Título (suporta HTML)')),
                ('hero_desc', models.TextField(default='Especializado em identidade visual e ilustração digital. Crio sistemas de marca com carácter — do conceito ao detalhe final.', verbose_name='Descrição do Hero')),
                ('stat1_number', models.CharField(default='34+', max_length=10, verbose_name='Nº Estatística 1')),
                ('stat1_label', models.CharField(default='Projetos', max_length=30, verbose_name='Label Estatística 1')),
                ('stat2_number', models.CharField(default='3', max_length=10, verbose_name='Nº Estatística 2')),
                ('stat2_label', models.CharField(default='Anos exp.', max_length=30, verbose_name='Label Estatística 2')),
                ('stat3_number', models.CharField(default='18', max_length=10, verbose_name='Nº Estatística 3')),
                ('stat3_label', models.CharField(default='Clientes', max_length=30, verbose_name='Label Estatística 3')),
                ('contact_email', models.EmailField(default='alex.morais@email.com', max_length=254, verbose_name='Email de Contacto')),
                ('link_behance', models.URLField(blank=True, default='#', null=True, verbose_name='Link Behance')),
                ('link_instagram', models.URLField(blank=True, default='#', null=True, verbose_name='Link Instagram')),
                ('link_linkedin', models.URLField(blank=True, default='#', null=True, verbose_name='Link LinkedIn')),
            ],
            options={
                'verbose_name': 'Configuração Geral',
                'verbose_name_plural': 'Configurações Gerais',
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ferramenta')),
                ('percentage', models.PositiveIntegerField(default=80, verbose_name='Percentagem (0-100)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Ferramenta',
                'verbose_name_plural': 'Ferramentas',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order'], 'verbose_name': 'Projeto', 'verbose_name_plural': 'Projetos'},
        ),
    ]
