# Generated by Django 4.2.30 on 2026-05-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_creativestep_generalsetting_tool_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalsetting',
            name='link_behance',
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='contact_email',
            field=models.EmailField(default='fredy.segunda@email.com', max_length=254, verbose_name='Email de Contacto'),
        ),
    ]
