# Generated by Django 4.2.30 on 2026-05-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_generalsetting_link_behance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsetting',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='cv_files/', verbose_name='Ficheiro do CV (PDF)'),
        ),
    ]
