# Generated by Django 4.2.30 on 2026-07-26 21:30

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_generalsetting_cv_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creativestep',
            options={'ordering': ['order'], 'verbose_name': 'Etapa de Trabalho', 'verbose_name_plural': '4. Processo Criativo'},
        ),
        migrations.AlterModelOptions(
            name='generalsetting',
            options={'verbose_name': 'Configuração Geral & Identidade', 'verbose_name_plural': '1. Configurações Gerais do Site'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['section', 'order'], 'verbose_name': 'Projeto do Portfólio', 'verbose_name_plural': '2. Gestão de Projetos & Obras'},
        ),
        migrations.AlterModelOptions(
            name='tool',
            options={'ordering': ['order'], 'verbose_name': 'Ferramenta / Competência', 'verbose_name_plural': '3. Stack de Ferramentas'},
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='availability_badge_text',
            field=models.CharField(default='Disponível para Projetos Freelance & Colaborações', max_length=120, verbose_name='Texto do Badge de Disponibilidade (Hero)'),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='cta_subtitle',
            field=models.TextField(default='Estou atualmente disponível para projetos freelance, novas marcas e parcerias criativas que valorizem design memorável e detalhista.', verbose_name='Subtítulo / Convite de Contacto'),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='cta_title',
            field=models.CharField(default='Pronto para dar vida ao seu próximo projeto?', max_length=150, verbose_name='Título do Bloco de Contacto'),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='is_available',
            field=models.BooleanField(default=True, help_text="Se ativo, exibe o indicador luminoso VERDE. Se desativar, exibe indicador de 'Agenda Ocupada' / em projeto.", verbose_name='Atualmente disponível para Freelance/Novos Projetos?'),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='link_behance',
            field=models.URLField(blank=True, default='#', null=True, verbose_name='Link Behance (Essencial para Design)'),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='link_dribbble',
            field=models.URLField(blank=True, default='#', null=True, verbose_name='Link Dribbble'),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='link_github',
            field=models.URLField(blank=True, null=True, verbose_name='Link GitHub / Outro Portfólio'),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='meta_description',
            field=models.TextField(default='Especializado em identidade visual e ilustração digital. Crio sistemas de marca com carácter — do conceito ao detalhe final.', verbose_name='Descrição SEO para Google e Partilhas'),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='site_title',
            field=models.CharField(default='Fredy Segunda — Direção Criativa & Design Gráfico', max_length=120, verbose_name='Título da Página (Browser & SEO)'),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Formato internacional com código do país. Ex: +351912345678 (permite conversa direta)', max_length=25, null=True, verbose_name='Número do WhatsApp'),
        ),
        migrations.AddField(
            model_name='project',
            name='client_name',
            field=models.CharField(blank=True, help_text='Ex: Nike, Estúdio Beta, Projeto Conceitual', max_length=100, null=True, verbose_name='Marca / Cliente'),
        ),
        migrations.AddField(
            model_name='project',
            name='featured_tag',
            field=models.CharField(blank=True, help_text='Ex: Premiado, Em Destaque, Rebrand 2026', max_length=50, null=True, verbose_name='Tag de Destaque'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_url',
            field=models.URLField(blank=True, help_text='Permite que o utilizador aceda ao estudo de caso ao vivo', null=True, verbose_name='Link do Projeto (Behance / Site Real)'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_year',
            field=models.CharField(blank=True, default='2026', max_length=10, null=True, verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='creativestep',
            name='description',
            field=models.TextField(verbose_name='Descrição Metodológica'),
        ),
        migrations.AlterField(
            model_name='creativestep',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição'),
        ),
        migrations.AlterField(
            model_name='creativestep',
            name='step_number',
            field=models.CharField(help_text='Ex: 01, 02, 03', max_length=10, verbose_name='Número do Passo'),
        ),
        migrations.AlterField(
            model_name='creativestep',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Título da Etapa'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='contact_email',
            field=models.EmailField(default='fredy.segunda@email.com', max_length=254, verbose_name='Email Principal de Contacto'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='cv_file',
            field=cloudinary.models.CloudinaryField(blank=True, help_text="Ficheiro disponibilizado para download no botão 'Transferir Currículo'", max_length=255, null=True, verbose_name='Ficheiro do Currículo (PDF/Asset)'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='hero_desc',
            field=models.TextField(default='Especializado em identidade visual e ilustração digital. Crio sistemas de marca com carácter — do conceito estético ao detalhe de acabamento final.', verbose_name='Descrição Narrativa do Hero'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='hero_title',
            field=models.TextField(default='Marcas que<br><span class="blue">ficam</span><br>na memória.', verbose_name='Título Principal do Hero (suporta HTML)'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='hero_year',
            field=models.CharField(default='2026', max_length=10, verbose_name='Ano em Destaque (Hero/Footer)'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='stat1_label',
            field=models.CharField(default='Projetos Concluídos', max_length=35, verbose_name='Rótulo Estatística 1'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='stat2_label',
            field=models.CharField(default='Anos Experiência', max_length=35, verbose_name='Rótulo Estatística 2'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='stat3_label',
            field=models.CharField(default='Clientes Atendidos', max_length=35, verbose_name='Rótulo Estatística 3'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, help_text='Ex: Identidade Visual, Motion Design, Packaging', max_length=60, null=True, verbose_name='Categoria / Serviço'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='Texto sempre visível nas novas cards editoriais', null=True, verbose_name='Descrição Narrativa & Desafio'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_video',
            field=models.BooleanField(default=False, help_text='Se ativo, reproduz automaticamente em mute na card e com som no Lightbox', verbose_name='O ficheiro é um vídeo MP4/Loop?'),
        ),
        migrations.AlterField(
            model_name='project',
            name='media_file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Asset (Imagem ou Vídeo MP4)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Define qual aparece primeiro na grelha', verbose_name='Ordem na Secção'),
        ),
        migrations.AlterField(
            model_name='project',
            name='section',
            field=models.CharField(choices=[('featured_main', '★ Destaque Principal (Showcase Amplo)'), ('featured_side', '■ Destaques Secundários (2 Cards)'), ('gallery_small', '❖ Galeria de Criações (Grid 3 Colunas)'), ('gallery_asym', '◆ Galeria Assimétrica (Conceitos/Assinatura)'), ('reel', '🎬 Clip de Animação / Vídeo Reel')], default='gallery_small', max_length=25, verbose_name='Secção no Site'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(blank=True, help_text='Nome da marca, projeto ou ilustração', max_length=120, null=True, verbose_name='Título do Trabalho'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='name',
            field=models.CharField(help_text='Ex: Adobe Illustrator, Branding, Cinema 4D', max_length=60, verbose_name='Ferramenta / Competência'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Menor número aparece primeiro', verbose_name='Ordem de Exibição'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='percentage',
            field=models.PositiveIntegerField(default=90, verbose_name='Nível de Domínio (0 a 100%)'),
        ),
    ]
