# Generated by Django 4.2.30 on 2026-07-26 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_creativestep_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Série Ilustração Nike, Branding para Hotelaria, Identidade Visual 2026', max_length=100, verbose_name='Nome da Galeria Específica')),
                ('tag', models.CharField(default='Coleção Especial', help_text='Ex: Coleção Especial, Série Exclusiva, Estudo de Caso', max_length=60, verbose_name='Tag Superior (Eyebrow)')),
                ('description', models.TextField(blank=True, help_text='Breve introdução sobre a curadoria e conceito desta galeria específica.', null=True, verbose_name='Descrição da Galeria')),
                ('layout_style', models.CharField(choices=[('grid3', '❖ Grelha de 3 Colunas (Cards Editoriais Clássicas)'), ('masonry', '◆ Galeria Assimétrica (Destaques Conceituais/Específicas)')], default='grid3', max_length=20, verbose_name='Estilo Visual na Página')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Ordem de Apresentação no Site')),
                ('is_active', models.BooleanField(default=True, verbose_name='Galeria Ativa no Site?')),
            ],
            options={
                'verbose_name': 'Galeria Temática Customizada',
                'verbose_name_plural': '3. Criar Galerias Específicas',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='creativestep',
            options={'ordering': ['order'], 'verbose_name': 'Etapa de Trabalho', 'verbose_name_plural': '5. Processo Criativo'},
        ),
        migrations.AlterModelOptions(
            name='generalsetting',
            options={'verbose_name': 'Configuração Geral & Identidade', 'verbose_name_plural': '1. Configurações & Personalização'},
        ),
        migrations.AlterModelOptions(
            name='tool',
            options={'ordering': ['order'], 'verbose_name': 'Ferramenta / Competência', 'verbose_name_plural': '4. Stack de Ferramentas'},
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='accent_color',
            field=models.CharField(choices=[('#4C75EE', 'Azul Índigo Studio (Padrão)'), ('#2563EB', 'Azul Cobalto Eléctrico'), ('#6366f1', 'Lilás Violeta Vibrante'), ('#8b5cf6', 'Roxo Awwwards Exclusive'), ('#10b981', 'Verde Esmeralda Luminoso'), ('#f59e0b', 'Dourado Âmbar Premium'), ('#f43f5e', 'Rosa Carmim Editorial'), ('#ffffff', 'Branco Puro Monocromático')], default='#4C75EE', max_length=20, verbose_name='Cor de Destaque (Accent/Luzes/Botões)'),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='bg_theme',
            field=models.CharField(choices=[('obsidian', '■ Obsidiana Profundo (Preto Puro Studio #08080c)'), ('midnight', '■ Azul Meia-Noite Cinematográfico (#050814)'), ('graphite', '■ Grafite Mineral & Slate (#0f1117)'), ('velvet', '■ Velvet Noir / Púrpura Imperial (#0a0712)'), ('emerald', '■ Esmeralda Noir / Verde Profundo (#040e0a)'), ('custom', '◆ Cor de Fundo Personalizada (Usar campo HEX)')], default='obsidian', max_length=20, verbose_name='Tema de Fundo do Site'),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='custom_bg_color',
            field=models.CharField(blank=True, default='#08080c', help_text="Ex: #0a0b10 (Ativo apenas quando seleciona 'Cor de Fundo Personalizada' acima)", max_length=20, null=True, verbose_name='Cor HEX Personalizada (Fundo)'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='link_behance',
            field=models.URLField(blank=True, default='#', null=True, verbose_name='Link Behance (Exibido no Topo, Hero e Dock Lateral)'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='link_dribbble',
            field=models.URLField(blank=True, default='#', null=True, verbose_name='Link Dribbble (Exibido no Topo e Dock Lateral)'),
        ),
        migrations.AddField(
            model_name='project',
            name='custom_gallery',
            field=models.ForeignKey(blank=True, help_text='Se selecionar uma de suas galerias customizadas aqui, este trabalho será exposto nela com destaque!', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='portfolio.customgallery', verbose_name='Ou alocar a Galeria Específica Criada'),
        ),
    ]
